/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Authenticates with email and password, returning a bearer token.
         *
         *     Problem types: `/problems/validation-error`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Log out current session */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["listUsers"];
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and returns a bearer token.
         *
         *     Problem types: `/problems/validation-error`, `/problems/email-taken`.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user avatar
         * @description Updates the authenticated user's avatar.
         *
         *     Problem types: `/problems/validation-error`.
         */
        patch: operations["updateAvatar"];
        trace?: never;
    };
    "/users/self/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user stats */
        get: operations["getMyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userID}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get stats for a specific user */
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/self/head-to-heads/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get head-to-head stats against an opponent
         * @description Returns head-to-head record, stats, and recent matches against the specified opponent.
         *
         *     Problem types: `/problems/self-comparison`.
         */
        get: operations["getHeadToHead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wordle-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a Wordle result
         * @description Parses a pasted Wordle share text and records the result.
         *
         *     Problem types: `/problems/invalid-wordle`, `/problems/duplicate-submission`.
         */
        post: operations["submitWordle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wordles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wordle archive (paginated) */
        get: operations["getArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wordles/{wordleID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single wordle with standings */
        get: operations["getArchiveWordle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboards/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current leaderboard */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionUser: {
            /**
             * Format: int64
             * @description Unique user identifier.
             */
            id: number;
            /** @description Display name. */
            name: string;
            /** @description Email address. */
            email: string;
            /** @description Avatar identifier ("01" through "25"). */
            avatar: string;
        };
        PublicUser: {
            /**
             * Format: int64
             * @description Unique user identifier.
             */
            id: number;
            /** @description Display name. */
            name: string;
            /** @description Avatar identifier ("01" through "25"). */
            avatar: string;
        };
        AuthResponse: {
            user: components["schemas"]["SessionUser"];
            /** @description Bearer token for authenticating subsequent requests. */
            token: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User email address.
             */
            email: string;
            /** @description User password. */
            password: string;
            /** @description Whether to issue a long-lived token. */
            remember_me?: boolean;
        };
        RegisterRequest: {
            /** @description Display name for the new user. */
            name: string;
            /**
             * Format: email
             * @description Email address (must be unique).
             */
            email: string;
            /** @description Password (minimum 8 characters). */
            password: string;
        };
        UpdateAvatarRequest: {
            /** @description Avatar ID, "01" through "25". */
            avatar: string;
        };
        WordleStats: {
            /** @description Total number of Wordle games played. */
            games: number;
            /** @description Number of games won (score 1-6). */
            wins: number;
            /** @description Number of games lost (score X). */
            fails: number;
            /**
             * Format: double
             * @description Mean score across all games (X counts as 7).
             */
            average_score: number;
            /**
             * Format: double
             * @description Percentage of games won (0-100).
             */
            win_percentage: number;
            /** @description Score distribution — keys are "1" through "6" and "X". */
            distribution: {
                [key: string]: number;
            };
            /** @description Current consecutive-win streak. */
            current_streak: number;
            /** @description Longest consecutive-win streak ever. */
            max_streak: number;
        };
        WordleEntry: {
            /**
             * Format: int64
             * @description Unique entry identifier.
             */
            id: number;
            /** @description Wordle puzzle number. */
            wordle_id: number;
            /** @description Result score: "1"-"6" or "X". */
            score: string;
            /** @description Original pasted Wordle share text. */
            raw_input: string;
            /**
             * Format: date-time
             * @description Timestamp when the entry was submitted.
             */
            created_at: string;
        };
        WordleSubmitRequest: {
            /** @description Pasted Wordle share text to parse and record. */
            raw_input: string;
        };
        ArchiveEntryInfo: {
            /** @description Result score: "1"-"6" or "X". */
            score: string;
            /**
             * Format: date-time
             * @description Timestamp when the entry was submitted.
             */
            created_at: string;
            /** @description Original pasted Wordle share text. */
            raw_input?: string;
        };
        ArchiveSummary: {
            /** @description Best score among all participants for this puzzle. */
            best_score: string;
            /** @description Number of participants who solved the puzzle. */
            solved_count: number;
            /** @description Number of participants who failed the puzzle. */
            failed_count: number;
        };
        ArchiveListItem: {
            /** @description Wordle puzzle number. */
            wordle_id: number;
            /** @description Number of users who submitted a result for this puzzle. */
            participant_count: number;
            /** @description Whether the authenticated user has submitted a result. */
            viewer_has_played: boolean;
            viewer_entry?: components["schemas"]["ArchiveEntryInfo"];
            summary?: components["schemas"]["ArchiveSummary"];
        };
        ArchiveListPage: {
            /** @description Absolute URI of the current page. */
            self: string;
            /** @description Absolute URI of the next page, absent if no more results. */
            next?: string;
            /** @description Wordle archive entries for this page. */
            items: components["schemas"]["ArchiveListItem"][];
        };
        ArchiveStanding: {
            user: components["schemas"]["PublicUser"];
            entry: components["schemas"]["ArchiveEntryInfo"];
        };
        ArchiveWordle: {
            /** @description Wordle puzzle number. */
            wordle_id: number;
            /** @description Total number of registered users. */
            total_users: number;
            /** @description Number of users who have submitted a result. */
            played_count: number;
            /** @description Number of users who have not yet submitted. */
            pending_count: number;
            /** @description Whether the authenticated user has submitted a result. */
            viewer_has_played: boolean;
            viewer_entry?: components["schemas"]["ArchiveEntryInfo"];
            /** @description Participants sorted by score. */
            standings: components["schemas"]["ArchiveStanding"][];
            /** @description Users who have not yet submitted. */
            waiting_players: components["schemas"]["PublicUser"][];
        };
        HeadToHeadRecord: {
            /** @description Total number of shared Wordle puzzles. */
            total_games: number;
            /** @description Games won against the opponent. */
            wins: number;
            /** @description Games lost against the opponent. */
            losses: number;
            /** @description Games tied with the opponent. */
            ties: number;
            /**
             * Format: double
             * @description Percentage of shared games won (0-100).
             */
            win_percentage: number;
        };
        RecentMatch: {
            /** @description Wordle puzzle number. */
            wordle_id: number;
            /** @description Authenticated user's score for this puzzle. */
            self_score: string;
            /** @description Opponent's score for this puzzle. */
            opponent_score: string;
            /**
             * Format: date-time
             * @description Timestamp of the most recent submission for this puzzle.
             */
            played_at: string;
            /**
             * @description Outcome from the authenticated user's perspective.
             * @enum {string}
             */
            result: "WIN" | "LOSS" | "TIE";
        };
        HeadToHeadStats: {
            opponent: components["schemas"]["PublicUser"];
            record: components["schemas"]["HeadToHeadRecord"];
            /** @description Wordle stats scoped to shared puzzles only. */
            stats: {
                self: components["schemas"]["WordleStats"];
                opponent: components["schemas"]["WordleStats"];
            };
            /** @description Most recent head-to-head matches. */
            recent_matches: components["schemas"]["RecentMatch"][];
        };
        LeaderboardEntry: {
            player: components["schemas"]["PublicUser"];
            /** @description Total number of shared Wordle games played. */
            total_games: number;
            /**
             * Format: double
             * @description Mean score across shared games (X counts as 7).
             */
            average_score: number;
            /**
             * Format: double
             * @description Percentage of shared games won (0-100).
             */
            win_percentage: number;
            /** @description Current consecutive-win streak. */
            current_streak: number;
            /** @description Longest consecutive-win streak ever. */
            max_streak: number;
        };
        LeaderboardData: {
            /** @description Number of Wordle puzzles where all players participated. */
            shared_wordles: number;
            /** @description Leaderboard entries sorted by rank. */
            items: components["schemas"]["LeaderboardEntry"][];
        };
        FieldError: {
            /** @description The name of the field that failed validation. */
            field: string;
            /** @description Human-readable description of the validation failure. */
            detail: string;
        };
        ProblemDetail: {
            /** @description A URI reference identifying the problem type. */
            type: string;
            /** @description A short human-readable summary. */
            title: string;
            /** @description The HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description A URI reference identifying the specific occurrence (request path). */
            instance?: string;
            /** @description Field-level validation errors. */
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PublicUser"][];
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Email already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvatarRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordleStats"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric user identifier. */
                userID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric user identifier. */
                userID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordleStats"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getHeadToHead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric user identifier. */
                userID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Head-to-head stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHeadStats"];
                };
            };
            /** @description Invalid opponent (e.g., comparing with yourself) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Opponent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    submitWordle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordleSubmitRequest"];
            };
        };
        responses: {
            /** @description Submission accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordleEntry"];
                };
            };
            /** @description Invalid format or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate submission */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getArchive: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return per page. */
                limit?: number;
                /** @description Opaque, base64-encoded cursor for pagination. Omit for the first page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveListPage"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArchiveWordle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wordle puzzle number. */
                wordleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wordle detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveWordle"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wordle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardData"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
