//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/icarofr/wordle-tracker/internal/auth"
	"github.com/icarofr/wordle-tracker/internal/users"
	"github.com/icarofr/wordle-tracker/internal/wordles"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ArchiveEntryInfo defines model for ArchiveEntryInfo.
type ArchiveEntryInfo = wordles.ArchiveEntry

// ArchiveListItem defines model for ArchiveListItem.
type ArchiveListItem = wordles.ArchiveListItem

// ArchiveListPage defines model for ArchiveListPage.
type ArchiveListPage = wordles.ArchiveListPage

// ArchiveStanding defines model for ArchiveStanding.
type ArchiveStanding = wordles.ArchiveStanding

// ArchiveSummary defines model for ArchiveSummary.
type ArchiveSummary = wordles.ArchiveSummary

// ArchiveWordle defines model for ArchiveWordle.
type ArchiveWordle = wordles.ArchiveDetail

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token Bearer token for authenticating subsequent requests.
	Token string      `json:"token"`
	User  SessionUser `json:"user"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Detail Human-readable description of the validation failure.
	Detail string `json:"detail"`

	// Field The name of the field that failed validation.
	Field string `json:"field"`
}

// HeadToHeadRecord defines model for HeadToHeadRecord.
type HeadToHeadRecord = wordles.HeadToHeadRecord

// HeadToHeadStats defines model for HeadToHeadStats.
type HeadToHeadStats struct {
	Opponent PublicUser `json:"opponent"`

	// RecentMatches Most recent head-to-head matches.
	RecentMatches []RecentMatch    `json:"recent_matches"`
	Record        HeadToHeadRecord `json:"record"`

	// Stats Wordle stats scoped to shared puzzles only.
	Stats struct {
		Opponent WordleStats `json:"opponent"`
		Self     WordleStats `json:"self"`
	} `json:"stats"`
}

// LeaderboardData defines model for LeaderboardData.
type LeaderboardData = wordles.LeaderboardData

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry = wordles.LeaderboardEntry

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email User email address.
	Email string `json:"email"`

	// Password User password.
	Password string `json:"password"`

	// RememberMe Whether to issue a long-lived token.
	RememberMe *bool `json:"remember_me,omitempty"`
}

// ProblemDetail defines model for ProblemDetail.
type ProblemDetail struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Instance A URI reference identifying the specific occurrence (request path).
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code.
	Status int32 `json:"status"`

	// Title A short human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// PublicUser defines model for PublicUser.
type PublicUser = users.User

// RecentMatch defines model for RecentMatch.
type RecentMatch = wordles.RecentMatch

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email address (must be unique).
	Email string `json:"email"`

	// Name Display name for the new user.
	Name string `json:"name"`

	// Password Password (minimum 8 characters).
	Password string `json:"password"`
}

// SessionUser defines model for SessionUser.
type SessionUser = auth.SessionUser

// UpdateAvatarRequest defines model for UpdateAvatarRequest.
type UpdateAvatarRequest struct {
	// Avatar Avatar ID, "01" through "25".
	Avatar string `json:"avatar"`
}

// WordleEntry defines model for WordleEntry.
type WordleEntry = wordles.Entry

// WordleStats defines model for WordleStats.
type WordleStats = wordles.Stats

// WordleSubmitRequest defines model for WordleSubmitRequest.
type WordleSubmitRequest struct {
	// RawInput Pasted Wordle share text to parse and record.
	RawInput string `json:"raw_input"`
}

// GetArchiveParams defines parameters for GetArchive.
type GetArchiveParams struct {
	// Limit Maximum number of items to return per page.
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque, base64-encoded cursor for pagination. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateAvatarJSONRequestBody defines body for UpdateAvatar for application/json ContentType.
type UpdateAvatarJSONRequestBody = UpdateAvatarRequest

// SubmitWordleJSONRequestBody defines body for SubmitWordle for application/json ContentType.
type SubmitWordleJSONRequestBody = WordleSubmitRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get current leaderboard
	// (GET /leaderboards/current)
	GetLeaderboard(w http.ResponseWriter, r *http.Request)
	// Log in with email and password
	// (POST /sessions)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out current session
	// (DELETE /sessions/current)
	Logout(w http.ResponseWriter, r *http.Request)
	// List all users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /users)
	Register(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /users/self)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Update current user avatar
	// (PATCH /users/self)
	UpdateAvatar(w http.ResponseWriter, r *http.Request)
	// Get head-to-head stats against an opponent
	// (GET /users/self/head-to-heads/{userID})
	GetHeadToHead(w http.ResponseWriter, r *http.Request, userID int64)
	// Get current user stats
	// (GET /users/self/stats)
	GetMyStats(w http.ResponseWriter, r *http.Request)
	// Get user by ID
	// (GET /users/{userID})
	GetUser(w http.ResponseWriter, r *http.Request, userID int64)
	// Get stats for a specific user
	// (GET /users/{userID}/stats)
	GetUserStats(w http.ResponseWriter, r *http.Request, userID int64)
	// Submit a Wordle result
	// (POST /wordle-submissions)
	SubmitWordle(w http.ResponseWriter, r *http.Request)
	// Get wordle archive (paginated)
	// (GET /wordles)
	GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams)
	// Get a single wordle with standings
	// (GET /wordles/{wordleID})
	GetArchiveWordle(w http.ResponseWriter, r *http.Request, wordleID int32)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetLeaderboard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeaderboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAvatar operation middleware
func (siw *ServerInterfaceWrapper) UpdateAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHeadToHead operation middleware
func (siw *ServerInterfaceWrapper) GetHeadToHead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHeadToHead(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyStats operation middleware
func (siw *ServerInterfaceWrapper) GetMyStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserStats operation middleware
func (siw *ServerInterfaceWrapper) GetUserStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserStats(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitWordle operation middleware
func (siw *ServerInterfaceWrapper) SubmitWordle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitWordle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchive operation middleware
func (siw *ServerInterfaceWrapper) GetArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArchiveParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchiveWordle operation middleware
func (siw *ServerInterfaceWrapper) GetArchiveWordle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wordleID" -------------
	var wordleID int32

	err = runtime.BindStyledParameterWithOptions("simple", "wordleID", r.PathValue("wordleID"), &wordleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wordleID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchiveWordle(w, r, wordleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/leaderboards/current", wrapper.GetLeaderboard)
	m.HandleFunc("POST "+options.BaseURL+"/sessions", wrapper.Login)
	m.HandleFunc("DELETE "+options.BaseURL+"/sessions/current", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.Register)
	m.HandleFunc("GET "+options.BaseURL+"/users/self", wrapper.GetCurrentUser)
	m.HandleFunc("PATCH "+options.BaseURL+"/users/self", wrapper.UpdateAvatar)
	m.HandleFunc("GET "+options.BaseURL+"/users/self/head-to-heads/{userID}", wrapper.GetHeadToHead)
	m.HandleFunc("GET "+options.BaseURL+"/users/self/stats", wrapper.GetMyStats)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userID}", wrapper.GetUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userID}/stats", wrapper.GetUserStats)
	m.HandleFunc("POST "+options.BaseURL+"/wordle-submissions", wrapper.SubmitWordle)
	m.HandleFunc("GET "+options.BaseURL+"/wordles", wrapper.GetArchive)
	m.HandleFunc("GET "+options.BaseURL+"/wordles/{wordleID}", wrapper.GetArchiveWordle)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboardRequestObject struct {
}

type GetLeaderboardResponseObject interface {
	VisitGetLeaderboardResponse(w http.ResponseWriter) error
}

type GetLeaderboard200JSONResponse LeaderboardData

func (response GetLeaderboard200JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboard401Response struct {
}

func (response GetLeaderboard401Response) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400ApplicationProblemPlusJSONResponse ProblemDetail

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401ApplicationProblemPlusJSONResponse ProblemDetail

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401Response struct {
}

func (response Logout401Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse struct {
	Items []PublicUser `json:"items"`
}

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListUsers401Response struct {
}

func (response ListUsers401Response) VisitListUsersResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Register400ApplicationProblemPlusJSONResponse ProblemDetail

func (response Register400ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Register409ApplicationProblemPlusJSONResponse ProblemDetail

func (response Register409ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse SessionUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401Response struct {
}

func (response GetCurrentUser401Response) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateAvatarRequestObject struct {
	Body *UpdateAvatarJSONRequestBody
}

type UpdateAvatarResponseObject interface {
	VisitUpdateAvatarResponse(w http.ResponseWriter) error
}

type UpdateAvatar200JSONResponse SessionUser

func (response UpdateAvatar200JSONResponse) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAvatar400ApplicationProblemPlusJSONResponse ProblemDetail

func (response UpdateAvatar400ApplicationProblemPlusJSONResponse) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAvatar401Response struct {
}

func (response UpdateAvatar401Response) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetHeadToHeadRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetHeadToHeadResponseObject interface {
	VisitGetHeadToHeadResponse(w http.ResponseWriter) error
}

type GetHeadToHead200JSONResponse HeadToHeadStats

func (response GetHeadToHead200JSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHeadToHead400ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetHeadToHead400ApplicationProblemPlusJSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHeadToHead401Response struct {
}

func (response GetHeadToHead401Response) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetHeadToHead404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetHeadToHead404ApplicationProblemPlusJSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMyStatsRequestObject struct {
}

type GetMyStatsResponseObject interface {
	VisitGetMyStatsResponse(w http.ResponseWriter) error
}

type GetMyStats200JSONResponse WordleStats

func (response GetMyStats200JSONResponse) VisitGetMyStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyStats401Response struct {
}

func (response GetMyStats401Response) VisitGetMyStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUserRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse PublicUser

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUser401Response struct {
}

func (response GetUser401Response) VisitGetUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUser404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetUser404ApplicationProblemPlusJSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUserStatsRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetUserStatsResponseObject interface {
	VisitGetUserStatsResponse(w http.ResponseWriter) error
}

type GetUserStats200JSONResponse WordleStats

func (response GetUserStats200JSONResponse) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserStats401Response struct {
}

func (response GetUserStats401Response) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUserStats404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetUserStats404ApplicationProblemPlusJSONResponse) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordleRequestObject struct {
	Body *SubmitWordleJSONRequestBody
}

type SubmitWordleResponseObject interface {
	VisitSubmitWordleResponse(w http.ResponseWriter) error
}

type SubmitWordle201JSONResponse WordleEntry

func (response SubmitWordle201JSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordle400ApplicationProblemPlusJSONResponse ProblemDetail

func (response SubmitWordle400ApplicationProblemPlusJSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordle401Response struct {
}

func (response SubmitWordle401Response) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SubmitWordle409ApplicationProblemPlusJSONResponse ProblemDetail

func (response SubmitWordle409ApplicationProblemPlusJSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetArchiveRequestObject struct {
	Params GetArchiveParams
}

type GetArchiveResponseObject interface {
	VisitGetArchiveResponse(w http.ResponseWriter) error
}

type GetArchive200JSONResponse ArchiveListPage

func (response GetArchive200JSONResponse) VisitGetArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchive401Response struct {
}

func (response GetArchive401Response) VisitGetArchiveResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetArchiveWordleRequestObject struct {
	WordleID int32 `json:"wordleID"`
}

type GetArchiveWordleResponseObject interface {
	VisitGetArchiveWordleResponse(w http.ResponseWriter) error
}

type GetArchiveWordle200JSONResponse ArchiveWordle

func (response GetArchiveWordle200JSONResponse) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchiveWordle401Response struct {
}

func (response GetArchiveWordle401Response) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetArchiveWordle404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetArchiveWordle404ApplicationProblemPlusJSONResponse) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get current leaderboard
	// (GET /leaderboards/current)
	GetLeaderboard(ctx context.Context, request GetLeaderboardRequestObject) (GetLeaderboardResponseObject, error)
	// Log in with email and password
	// (POST /sessions)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Log out current session
	// (DELETE /sessions/current)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// List all users
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// Register a new user
	// (POST /users)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Get current authenticated user
	// (GET /users/self)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Update current user avatar
	// (PATCH /users/self)
	UpdateAvatar(ctx context.Context, request UpdateAvatarRequestObject) (UpdateAvatarResponseObject, error)
	// Get head-to-head stats against an opponent
	// (GET /users/self/head-to-heads/{userID})
	GetHeadToHead(ctx context.Context, request GetHeadToHeadRequestObject) (GetHeadToHeadResponseObject, error)
	// Get current user stats
	// (GET /users/self/stats)
	GetMyStats(ctx context.Context, request GetMyStatsRequestObject) (GetMyStatsResponseObject, error)
	// Get user by ID
	// (GET /users/{userID})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
	// Get stats for a specific user
	// (GET /users/{userID}/stats)
	GetUserStats(ctx context.Context, request GetUserStatsRequestObject) (GetUserStatsResponseObject, error)
	// Submit a Wordle result
	// (POST /wordle-submissions)
	SubmitWordle(ctx context.Context, request SubmitWordleRequestObject) (SubmitWordleResponseObject, error)
	// Get wordle archive (paginated)
	// (GET /wordles)
	GetArchive(ctx context.Context, request GetArchiveRequestObject) (GetArchiveResponseObject, error)
	// Get a single wordle with standings
	// (GET /wordles/{wordleID})
	GetArchiveWordle(ctx context.Context, request GetArchiveWordleRequestObject) (GetArchiveWordleResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLeaderboard operation middleware
func (sh *strictHandler) GetLeaderboard(w http.ResponseWriter, r *http.Request) {
	var request GetLeaderboardRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaderboard(ctx, request.(GetLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaderboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLeaderboardResponseObject); ok {
		if err := validResponse.VisitGetLeaderboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAvatar operation middleware
func (sh *strictHandler) UpdateAvatar(w http.ResponseWriter, r *http.Request) {
	var request UpdateAvatarRequestObject

	var body UpdateAvatarJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAvatar(ctx, request.(UpdateAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAvatarResponseObject); ok {
		if err := validResponse.VisitUpdateAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHeadToHead operation middleware
func (sh *strictHandler) GetHeadToHead(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetHeadToHeadRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHeadToHead(ctx, request.(GetHeadToHeadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHeadToHead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHeadToHeadResponseObject); ok {
		if err := validResponse.VisitGetHeadToHeadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyStats operation middleware
func (sh *strictHandler) GetMyStats(w http.ResponseWriter, r *http.Request) {
	var request GetMyStatsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyStats(ctx, request.(GetMyStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyStatsResponseObject); ok {
		if err := validResponse.VisitGetMyStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetUserRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserStats operation middleware
func (sh *strictHandler) GetUserStats(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetUserStatsRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserStats(ctx, request.(GetUserStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserStatsResponseObject); ok {
		if err := validResponse.VisitGetUserStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitWordle operation middleware
func (sh *strictHandler) SubmitWordle(w http.ResponseWriter, r *http.Request) {
	var request SubmitWordleRequestObject

	var body SubmitWordleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitWordle(ctx, request.(SubmitWordleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitWordle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitWordleResponseObject); ok {
		if err := validResponse.VisitSubmitWordleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchive operation middleware
func (sh *strictHandler) GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams) {
	var request GetArchiveRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchive(ctx, request.(GetArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArchiveResponseObject); ok {
		if err := validResponse.VisitGetArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchiveWordle operation middleware
func (sh *strictHandler) GetArchiveWordle(w http.ResponseWriter, r *http.Request, wordleID int32) {
	var request GetArchiveWordleRequestObject

	request.WordleID = wordleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchiveWordle(ctx, request.(GetArchiveWordleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchiveWordle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArchiveWordleResponseObject); ok {
		if err := validResponse.VisitGetArchiveWordleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rc627cNvZ/FUL/ArXx11ycptnW39Im2xhwGiNOtgVir8uRzkhsJFIhKdvT7AD7EPuE",
	"+yQLXiRREjWjcTxugn5p45F4O+d3bj+emY9BxPKCUaBSBMcfAxGlkGP9z6c8Ssk1PKeSr07okqnPCs4K",
	"4JKAfiPigCXEV1iqv2IQESeFJIwGx8EbkoOQOC/QTQoUyRQQqJnQDRZIlIucSAnxNAiDJeO5miGIsYSJ",
	"JDkEYSBXBQTHgZCc0CRYhwHHN1eEFqVnqVecJITiDBVYSIjRL4zHGSCRYg5Iwq2c+iYUEePQn+w1iDKT",
	"SD89RhfB0UUwuQieXASIcXQR/HoReGZT+4MPJeEQB8fv7NShK5/Legxb/A6RDMLgdpKwif3wRm9ZTF2Z",
	"u69MSF4wrs9eYJkGx0FCZFouphHLZyTCnC35zEwykRxH74HPCJXAKc7s50Jv0y5wSoQ8kZD3dVpgLklE",
	"CkzlVcRK6pH3z2W+AI7YEpUCuEA3KWs0ijDiRoRLxpFMiUBF+ccfGbRUTah88riRo9pqAlyrpcxzzFdq",
	"1a84LIPj4P9mDURnFp8ze45z+/Y6DK4J3AC/0iAbObqBdjM+xeKqyPBKabJ78F9SkClwDWZcyhSoJJHS",
	"sBYESl1k13Jw4LJgLANM1WpGJ1fEt4qBr5EaolrYXeF988gjvA4KmyVCj1Z9B94NpDWG9ozTM5xAH6dE",
	"Qi4GhYfNcO1yCAgHizjRSKyHj4BJfdB1LR/MOdaoo3DrsZCnC8GyUgJ6+/pE2YkCjHpTLx8ivBBAJSJL",
	"RBnKGQcLFeF3VJAtxy0RlZyriatDbvFSat5KErurXqtlj6o/l5jGat891d/ZxJWVbht3Vi4yEr0VHoPS",
	"w0O7/G4Cqw+zT4E1nrMtrwWIEb7ccRECSQKxNRpAarwJiCN9uF5wIL7+UE+GcM5ognCWtdf2xI2eTSwx",
	"ySDe8VAqTpmB+li7hSWWXd9pQTNw1wU7yHMEGrrq7OyrI5cdIWrhs0eEGufsyTlAG8cu+UaKrwFRJtEK",
	"5EA6OaxME+52Xs4f28eAx1q/J16duXgRjKvZF6vG2naJU7WT8cQpySTOrvSBPLm6emgzDXVuDgkRErhN",
	"bMTIY35hGRgmUoFOL+WTytsRYBulHjek9DXzwJmgC4SOJYQdQ/RpxAVzX4a7eZxnIDHJ9uNwSpm+BlEw",
	"Kjz+RrL3QH2hCXOFLfVURyEHYYQmSvMCPpQqw1LSBTGQsI1JM85BCMLopjzD7LIn0nUY/J1AFj/nnPH+",
	"2WIj1N7hXpQ5phMOOMaLDJDzsMoer3FGYqw/UWGk5AOhVy3u8SEqxcU5VLPp15BMsaxibjP/9tzULBJW",
	"p/EJ4QXg+A1T/30NEeNxXxQZEwI8hv0TzkGgjAmJcIIJFVLvmBVGSSO9XSPw/tw6fbohMr3TxNpCEzXR",
	"dletSY6a8jCeYqy/viH0qgAeAZW2xOrEpvqZs5LeF7phFB3MJ0fz+WGbwmHlInP4G7NRu9iguNRsd9ZE",
	"Bzmu9OyqYYUEq7TeyUe6rR7i9uG5mkXOJTacXBvVlXB2izoc1GGvciyj1Ierl8oazEsoBRxPJJuo/yM7",
	"YnSwe63neKlG+aIdr2110yQ9SZskSg4X/PqpSpsKlWyzCq3WIBCj2Uod4W6iNGsYfTgF+egh/sK7Xr3v",
	"3ToD6jdr+VXi6CnW5ylPAcfAFwzz+BmWeDSX4oyriZQmReWYvh+NCmcqw216oGFUdlUZw4a8vO3t0E0K",
	"qppUdaTJQ5oqbGxN0NVQeys7kiRdee/DTfQE2lMqvgaOExiqw18CplUdHnEmRNvBH/yKdBIoEBbob2Od",
	"vCWgroTkgN/3F/3RElSRysuiUpJrmNwQisz7I8NWjm8HFzhlNAExtACC634CvalG5Dum9neP3EbqJsn+",
	"/MJ3xzysbMJOsG0jrrfBHjxaqtzdtvZ3SXLKEkJfmxTfQz/m3gRbgQDpZwjHMQfRTsPMKE8+XWAhbmxM",
	"9MxYPVaT5YSeAk3U0Y58V2SQg9LXVQ4bKmeGiBAlIIwyRpNJRjQ9pWoNX53c0Xx1inrTvnhzxtkig/xZ",
	"XYncqUKB2yLD1NQjooCILEmkdq+pQRYZLEX+GgVUbeSxQV04TTK4hswtd8zro4OZU355wpjKYjGNPCp4",
	"qrl6DkvQO0ckVsXlcqVqS5X21qdsTocObKWJFKIP/fcDEstS+CuyF2/enCHzAopYDKPYA5Umy8x7AJEy",
	"LlHa1pS9svNuznywqyQKgyCkRm8vFvXTatO1PLzIbNy1J15iiblnr/rzaosEODq4COZHFwGSKWdlkqKL",
	"4NG3F4FfOT5a5y0lH0owjFUz7Uivr2rs/pTPiFBOWVfg2wWmiSA9UVgde4v7NTTgW0NM3I/DNRSU2ppb",
	"MgyWO0N5zCv7/Gths5kx1weW9trct2CJjNypjDT3p4mbjbfbmxsZNCfpOUgpI5YDWnKWD/CbXwtUAFdu",
	"QiU2U30XVeZKo7+c/ByEwemr8/MgDN6cPHf02b5IHBLjU99i4wX6wCSmc5KwixBXu7W0R2YXLhL3kVi8",
	"tsT6rrnFczetQAd5KSRaACq1Izkcl2dsdxz1hR+FGw2BETnHcPZyZp+gg5xQkpc5+g5FKeY4ksDFYWfu",
	"77b5LOuuRiUgLrn6QH5+jOK+zABRSXxcoFBOa+rK/77MSE2s9/m2UO7VaGvQjrYo+eRZiLzK1RwRlmrN",
	"4Dj458H83dHk+8t/Hb2bq/89ejeffHt5+NVW+Q3Jah1adzhQsz9kQ90G4Jl5d0beZ92i9yAxSttNK1DZ",
	"kNSI5i5dgfurdF2a8tMZJJxlnz99FBMFiUVp5vwY4Dgm6t84O2udfsxUrd2da1G406P//vs/6D2sBFIw",
	"10B1/I0CLKZxD7GNr1hikm0kQpPmJuvAaOLXw5FiGMlS3Z2eehiabjcS7H4vr7p60PMaNRxNnhzehXju",
	"3FsZAIxg1lqgvhei7dzeL+zN5+iINRjAN8SSs4EQgiRDBeYCtFWZi5LtqU6zkPcaRsGTE7k6j1KwBmPa",
	"BFTBVDfMa8pMf9ysl0pZBOu1ZoRM83znGJxcYwnVOSKWFyC1J0JPz050Lv5o8qS60pjWBEcdrd4YIau3",
	"gzC4Bi7MxEfT+XSuUMsKoLggwXHwzXQ+/cakNqk+wywFnJkDJCBNnQ1cs2EncXAc/ATyhXlDl1C6j0IP",
	"fDSf60SFUWkvznBRZLpDgtHZ78L4VMOU9bXaUFVwi/NCn4a9396pOsTorPtOGPg1iQARgcwRVy01Bsfv",
	"Lp0e88AcEkUpRHobOBFqQSudSzV0ljWUs5hZy9okOIei/lTpjbxS07dMHmG4O1mHweP5kceJMdlmGrry",
	"agP+3eW6JcCfQNZtx1nr4JUs3U+NQIUpD0zGwYTczEYI00hhmXUa14x4iDjIklNCE4TRwmnemV7QC3rm",
	"cIjiGP02s6SimDXM70Qzv79NL6jmEVxF6juAwOAQhPyBxav7U517v7Buo13yEtZ7hE2rM8qHGbU3JMoo",
	"AiGWZWaAs2l9K9f/320f7UsCz0b+0eHnHQQ/7EZOqAYMijjoighnYqNPOWUJInQItY5l6JK2bRKuf4kh",
	"Awl9F3PKElbKvmt57MuzkgRipF7fk/2rw7Ky8QH2IP5T1u2nXtd5SoR8a/sS7zHm1Fc6n9yr2S32/D0B",
	"HgTpi7yMiP1pgQipq6+qr7MSvvn7ch0OONofdS0qEK45P4QjXbnZJEo5WPGJ7jV0n2qLmEj8HqjX71YU",
	"6Z5cb5eBHeV9jx7M+5rtcXvr+bk64e8ffiOWSM044HiFNHw2OuFKzw6yN/ikWdXSNZTTWebBMpp7C87t",
	"ruCeECr+o7Tuad8JXf8Gyu9aqpu7jtfTRK0YvssyLOl9JGsuJ7wnx+GjnR84dduCDrPD2EHH55W13StM",
	"zWFrpJrIVem/C9G2nc/c/lYx+6ienDxbO+bf9ckmCLbaYg29EJq+07BiHNRWbCdmq6HZdnaoVKxqbd6M",
	"erXPiZI/5kQwf6Q0NbrtkzXf8cU5SJ1ivfNwVcBJ5LtTIuq5pnSqy6PAiCTogjt0ULKd2brcoyl0u6Q9",
	"SHzhqktUvbt/ilFUFUSlfHQA02QaIqtgmphiYcVKrhR/uIvRqDcfP/yRqrYL/bWoJSvpHcJM2tNQbTSY",
	"Iqfp2aFl6gF9s64bxIeC+MvVed00vSdcttu+/YWAg8X9hu+yWa2RYcXEuuLzuMCe8Gzq81dyMq2vgnt1",
	"+QUYqobcJxip1uVihbSmhgNrBaHtVqg2VNnhXwlNe3ENXyiojLPXX7Fsul479UXbUdmLpaYBbwN7fIa5",
	"0JzGULOBc0FkyhP7PeHNORkxUXxittJmNeLSyNzdoTdpM9de9ovw+6lUfPdrD0xzuE0uvkuapo0SRxEU",
	"NZT/xNzMOAfEeK8xfFd7/BPYkWcV/JwO1d2s0sAF4cpYbN/kZnPc6Oftl7y3efmX+FY3BzYtB5pXRZJZ",
	"9hEV+lsQ9md71JAPJeh2GOv5M5IT/VMYtSxjWGLdY/vt3NPDk5sVg+Oj+Vz3INq/fJfz/W5j/KGEEC2w",
	"gCePJ0AjFkOsMi7BuHZoBU6I+dbCFL1SIq2aKpeEC7nxIGaW1km696L7DFDd3/bx4My+ok+xzwz2pv0r",
	"TgdWqBAfbkPk7KP5x5Zstv2DJFsgOtQd5slCqsVH5yH+rrIHULM9ukfJ9rj2azqffzJi9/sJ6QhGgtAk",
	"gwp3uhp3f+fCAzm9Br+uEFPyLDgOZsH6cv2/AAAA//+XpcOQU1EAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
