//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/icarofr/wordle-tracker/internal/auth"
	"github.com/icarofr/wordle-tracker/internal/users"
	"github.com/icarofr/wordle-tracker/internal/wordles"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ArchiveEntryInfo defines model for ArchiveEntryInfo.
type ArchiveEntryInfo = wordles.ArchiveEntry

// ArchiveListItem defines model for ArchiveListItem.
type ArchiveListItem = wordles.ArchiveListItem

// ArchiveListPage defines model for ArchiveListPage.
type ArchiveListPage = wordles.ArchiveListPage

// ArchiveStanding defines model for ArchiveStanding.
type ArchiveStanding = wordles.ArchiveStanding

// ArchiveSummary defines model for ArchiveSummary.
type ArchiveSummary = wordles.ArchiveSummary

// ArchiveWordle defines model for ArchiveWordle.
type ArchiveWordle = wordles.ArchiveDetail

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	User SessionUser `json:"user"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Detail Human-readable description of the validation failure.
	Detail string `json:"detail"`

	// Field The name of the field that failed validation.
	Field string `json:"field"`
}

// HeadToHeadRecord defines model for HeadToHeadRecord.
type HeadToHeadRecord = wordles.HeadToHeadRecord

// HeadToHeadStats defines model for HeadToHeadStats.
type HeadToHeadStats struct {
	Opponent PublicUser `json:"opponent"`

	// RecentMatches Most recent head-to-head matches.
	RecentMatches []RecentMatch    `json:"recent_matches"`
	Record        HeadToHeadRecord `json:"record"`

	// Stats Wordle stats scoped to shared puzzles only.
	Stats struct {
		Opponent WordleStats `json:"opponent"`
		Self     WordleStats `json:"self"`
	} `json:"stats"`
}

// LeaderboardData defines model for LeaderboardData.
type LeaderboardData = wordles.LeaderboardData

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry = wordles.LeaderboardEntry

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email User email address.
	Email string `json:"email"`

	// Password User password.
	Password string `json:"password"`

	// RememberMe Whether to issue a long-lived token.
	RememberMe *bool `json:"remember_me,omitempty"`
}

// ProblemDetail defines model for ProblemDetail.
type ProblemDetail struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Instance A URI reference identifying the specific occurrence (request path).
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code.
	Status int32 `json:"status"`

	// Title A short human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// PublicUser defines model for PublicUser.
type PublicUser = users.User

// RecentMatch defines model for RecentMatch.
type RecentMatch = wordles.RecentMatch

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email address (must be unique).
	Email string `json:"email"`

	// Name Display name for the new user.
	Name string `json:"name"`

	// Password Password (minimum 8 characters).
	Password string `json:"password"`
}

// SessionUser defines model for SessionUser.
type SessionUser = auth.SessionUser

// UpdateAvatarRequest defines model for UpdateAvatarRequest.
type UpdateAvatarRequest struct {
	// Avatar Avatar ID, "01" through "25".
	Avatar string `json:"avatar"`
}

// WordleEntry defines model for WordleEntry.
type WordleEntry = wordles.Entry

// WordleStats defines model for WordleStats.
type WordleStats = wordles.Stats

// WordleSubmitRequest defines model for WordleSubmitRequest.
type WordleSubmitRequest struct {
	// RawInput Pasted Wordle share text to parse and record.
	RawInput string `json:"raw_input"`
}

// GetArchiveParams defines parameters for GetArchive.
type GetArchiveParams struct {
	// Limit Maximum number of items to return per page.
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque, base64-encoded cursor for pagination. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateAvatarJSONRequestBody defines body for UpdateAvatar for application/json ContentType.
type UpdateAvatarJSONRequestBody = UpdateAvatarRequest

// SubmitWordleJSONRequestBody defines body for SubmitWordle for application/json ContentType.
type SubmitWordleJSONRequestBody = WordleSubmitRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get current leaderboard
	// (GET /leaderboards/current)
	GetLeaderboard(w http.ResponseWriter, r *http.Request)
	// Log in with email and password
	// (POST /sessions)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out current session
	// (DELETE /sessions/current)
	Logout(w http.ResponseWriter, r *http.Request)
	// List all users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /users)
	Register(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /users/self)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Update current user avatar
	// (PATCH /users/self)
	UpdateAvatar(w http.ResponseWriter, r *http.Request)
	// Get head-to-head stats against an opponent
	// (GET /users/self/head-to-heads/{userID})
	GetHeadToHead(w http.ResponseWriter, r *http.Request, userID int64)
	// Get current user stats
	// (GET /users/self/stats)
	GetMyStats(w http.ResponseWriter, r *http.Request)
	// Get user by ID
	// (GET /users/{userID})
	GetUser(w http.ResponseWriter, r *http.Request, userID int64)
	// Get stats for a specific user
	// (GET /users/{userID}/stats)
	GetUserStats(w http.ResponseWriter, r *http.Request, userID int64)
	// Submit a Wordle result
	// (POST /wordle-submissions)
	SubmitWordle(w http.ResponseWriter, r *http.Request)
	// Get wordle archive (paginated)
	// (GET /wordles)
	GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams)
	// Get a single wordle with standings
	// (GET /wordles/{wordleID})
	GetArchiveWordle(w http.ResponseWriter, r *http.Request, wordleID int32)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetLeaderboard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeaderboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAvatar operation middleware
func (siw *ServerInterfaceWrapper) UpdateAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHeadToHead operation middleware
func (siw *ServerInterfaceWrapper) GetHeadToHead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHeadToHead(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyStats operation middleware
func (siw *ServerInterfaceWrapper) GetMyStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserStats operation middleware
func (siw *ServerInterfaceWrapper) GetUserStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int64

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserStats(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitWordle operation middleware
func (siw *ServerInterfaceWrapper) SubmitWordle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitWordle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchive operation middleware
func (siw *ServerInterfaceWrapper) GetArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArchiveParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchiveWordle operation middleware
func (siw *ServerInterfaceWrapper) GetArchiveWordle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wordleID" -------------
	var wordleID int32

	err = runtime.BindStyledParameterWithOptions("simple", "wordleID", r.PathValue("wordleID"), &wordleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wordleID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchiveWordle(w, r, wordleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/leaderboards/current", wrapper.GetLeaderboard)
	m.HandleFunc("POST "+options.BaseURL+"/sessions", wrapper.Login)
	m.HandleFunc("DELETE "+options.BaseURL+"/sessions/current", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.Register)
	m.HandleFunc("GET "+options.BaseURL+"/users/self", wrapper.GetCurrentUser)
	m.HandleFunc("PATCH "+options.BaseURL+"/users/self", wrapper.UpdateAvatar)
	m.HandleFunc("GET "+options.BaseURL+"/users/self/head-to-heads/{userID}", wrapper.GetHeadToHead)
	m.HandleFunc("GET "+options.BaseURL+"/users/self/stats", wrapper.GetMyStats)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userID}", wrapper.GetUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{userID}/stats", wrapper.GetUserStats)
	m.HandleFunc("POST "+options.BaseURL+"/wordle-submissions", wrapper.SubmitWordle)
	m.HandleFunc("GET "+options.BaseURL+"/wordles", wrapper.GetArchive)
	m.HandleFunc("GET "+options.BaseURL+"/wordles/{wordleID}", wrapper.GetArchiveWordle)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboardRequestObject struct {
}

type GetLeaderboardResponseObject interface {
	VisitGetLeaderboardResponse(w http.ResponseWriter) error
}

type GetLeaderboard200JSONResponse LeaderboardData

func (response GetLeaderboard200JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboard401Response struct {
}

func (response GetLeaderboard401Response) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400ApplicationProblemPlusJSONResponse ProblemDetail

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401ApplicationProblemPlusJSONResponse ProblemDetail

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401Response struct {
}

func (response Logout401Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse struct {
	Items []PublicUser `json:"items"`
}

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListUsers401Response struct {
}

func (response ListUsers401Response) VisitListUsersResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Register400ApplicationProblemPlusJSONResponse ProblemDetail

func (response Register400ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Register409ApplicationProblemPlusJSONResponse ProblemDetail

func (response Register409ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse SessionUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401Response struct {
}

func (response GetCurrentUser401Response) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateAvatarRequestObject struct {
	Body *UpdateAvatarJSONRequestBody
}

type UpdateAvatarResponseObject interface {
	VisitUpdateAvatarResponse(w http.ResponseWriter) error
}

type UpdateAvatar200JSONResponse SessionUser

func (response UpdateAvatar200JSONResponse) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAvatar400ApplicationProblemPlusJSONResponse ProblemDetail

func (response UpdateAvatar400ApplicationProblemPlusJSONResponse) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAvatar401Response struct {
}

func (response UpdateAvatar401Response) VisitUpdateAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetHeadToHeadRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetHeadToHeadResponseObject interface {
	VisitGetHeadToHeadResponse(w http.ResponseWriter) error
}

type GetHeadToHead200JSONResponse HeadToHeadStats

func (response GetHeadToHead200JSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHeadToHead400ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetHeadToHead400ApplicationProblemPlusJSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHeadToHead401Response struct {
}

func (response GetHeadToHead401Response) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetHeadToHead404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetHeadToHead404ApplicationProblemPlusJSONResponse) VisitGetHeadToHeadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMyStatsRequestObject struct {
}

type GetMyStatsResponseObject interface {
	VisitGetMyStatsResponse(w http.ResponseWriter) error
}

type GetMyStats200JSONResponse WordleStats

func (response GetMyStats200JSONResponse) VisitGetMyStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyStats401Response struct {
}

func (response GetMyStats401Response) VisitGetMyStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUserRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse PublicUser

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUser401Response struct {
}

func (response GetUser401Response) VisitGetUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUser404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetUser404ApplicationProblemPlusJSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUserStatsRequestObject struct {
	UserID int64 `json:"userID"`
}

type GetUserStatsResponseObject interface {
	VisitGetUserStatsResponse(w http.ResponseWriter) error
}

type GetUserStats200JSONResponse WordleStats

func (response GetUserStats200JSONResponse) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserStats401Response struct {
}

func (response GetUserStats401Response) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetUserStats404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetUserStats404ApplicationProblemPlusJSONResponse) VisitGetUserStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordleRequestObject struct {
	Body *SubmitWordleJSONRequestBody
}

type SubmitWordleResponseObject interface {
	VisitSubmitWordleResponse(w http.ResponseWriter) error
}

type SubmitWordle201JSONResponse WordleEntry

func (response SubmitWordle201JSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordle400ApplicationProblemPlusJSONResponse ProblemDetail

func (response SubmitWordle400ApplicationProblemPlusJSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SubmitWordle401Response struct {
}

func (response SubmitWordle401Response) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SubmitWordle409ApplicationProblemPlusJSONResponse ProblemDetail

func (response SubmitWordle409ApplicationProblemPlusJSONResponse) VisitSubmitWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetArchiveRequestObject struct {
	Params GetArchiveParams
}

type GetArchiveResponseObject interface {
	VisitGetArchiveResponse(w http.ResponseWriter) error
}

type GetArchive200JSONResponse ArchiveListPage

func (response GetArchive200JSONResponse) VisitGetArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchive401Response struct {
}

func (response GetArchive401Response) VisitGetArchiveResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetArchiveWordleRequestObject struct {
	WordleID int32 `json:"wordleID"`
}

type GetArchiveWordleResponseObject interface {
	VisitGetArchiveWordleResponse(w http.ResponseWriter) error
}

type GetArchiveWordle200JSONResponse ArchiveWordle

func (response GetArchiveWordle200JSONResponse) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchiveWordle401Response struct {
}

func (response GetArchiveWordle401Response) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetArchiveWordle404ApplicationProblemPlusJSONResponse ProblemDetail

func (response GetArchiveWordle404ApplicationProblemPlusJSONResponse) VisitGetArchiveWordleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get current leaderboard
	// (GET /leaderboards/current)
	GetLeaderboard(ctx context.Context, request GetLeaderboardRequestObject) (GetLeaderboardResponseObject, error)
	// Log in with email and password
	// (POST /sessions)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Log out current session
	// (DELETE /sessions/current)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// List all users
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// Register a new user
	// (POST /users)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Get current authenticated user
	// (GET /users/self)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Update current user avatar
	// (PATCH /users/self)
	UpdateAvatar(ctx context.Context, request UpdateAvatarRequestObject) (UpdateAvatarResponseObject, error)
	// Get head-to-head stats against an opponent
	// (GET /users/self/head-to-heads/{userID})
	GetHeadToHead(ctx context.Context, request GetHeadToHeadRequestObject) (GetHeadToHeadResponseObject, error)
	// Get current user stats
	// (GET /users/self/stats)
	GetMyStats(ctx context.Context, request GetMyStatsRequestObject) (GetMyStatsResponseObject, error)
	// Get user by ID
	// (GET /users/{userID})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
	// Get stats for a specific user
	// (GET /users/{userID}/stats)
	GetUserStats(ctx context.Context, request GetUserStatsRequestObject) (GetUserStatsResponseObject, error)
	// Submit a Wordle result
	// (POST /wordle-submissions)
	SubmitWordle(ctx context.Context, request SubmitWordleRequestObject) (SubmitWordleResponseObject, error)
	// Get wordle archive (paginated)
	// (GET /wordles)
	GetArchive(ctx context.Context, request GetArchiveRequestObject) (GetArchiveResponseObject, error)
	// Get a single wordle with standings
	// (GET /wordles/{wordleID})
	GetArchiveWordle(ctx context.Context, request GetArchiveWordleRequestObject) (GetArchiveWordleResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLeaderboard operation middleware
func (sh *strictHandler) GetLeaderboard(w http.ResponseWriter, r *http.Request) {
	var request GetLeaderboardRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaderboard(ctx, request.(GetLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaderboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLeaderboardResponseObject); ok {
		if err := validResponse.VisitGetLeaderboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAvatar operation middleware
func (sh *strictHandler) UpdateAvatar(w http.ResponseWriter, r *http.Request) {
	var request UpdateAvatarRequestObject

	var body UpdateAvatarJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAvatar(ctx, request.(UpdateAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAvatarResponseObject); ok {
		if err := validResponse.VisitUpdateAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHeadToHead operation middleware
func (sh *strictHandler) GetHeadToHead(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetHeadToHeadRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHeadToHead(ctx, request.(GetHeadToHeadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHeadToHead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHeadToHeadResponseObject); ok {
		if err := validResponse.VisitGetHeadToHeadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyStats operation middleware
func (sh *strictHandler) GetMyStats(w http.ResponseWriter, r *http.Request) {
	var request GetMyStatsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyStats(ctx, request.(GetMyStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyStatsResponseObject); ok {
		if err := validResponse.VisitGetMyStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetUserRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserStats operation middleware
func (sh *strictHandler) GetUserStats(w http.ResponseWriter, r *http.Request, userID int64) {
	var request GetUserStatsRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserStats(ctx, request.(GetUserStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserStatsResponseObject); ok {
		if err := validResponse.VisitGetUserStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitWordle operation middleware
func (sh *strictHandler) SubmitWordle(w http.ResponseWriter, r *http.Request) {
	var request SubmitWordleRequestObject

	var body SubmitWordleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitWordle(ctx, request.(SubmitWordleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitWordle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitWordleResponseObject); ok {
		if err := validResponse.VisitSubmitWordleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchive operation middleware
func (sh *strictHandler) GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams) {
	var request GetArchiveRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchive(ctx, request.(GetArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArchiveResponseObject); ok {
		if err := validResponse.VisitGetArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchiveWordle operation middleware
func (sh *strictHandler) GetArchiveWordle(w http.ResponseWriter, r *http.Request, wordleID int32) {
	var request GetArchiveWordleRequestObject

	request.WordleID = wordleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchiveWordle(ctx, request.(GetArchiveWordleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchiveWordle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArchiveWordleResponseObject); ok {
		if err := validResponse.VisitGetArchiveWordleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rc627cNvZ/FUL/ArXx11ycptnW39Im2xhwGiNOtgVir8uRzkisJVIhKTvT7AD7EPuE",
	"+yQLXiRREjWjcTxugn5p45F4O+d3bj+emY9BxPKCUaBSBMcfAxGlkGP9z6c8SskNPKeSr07okqnPCs4K",
	"4JKAfiPigCXEV1iqv2IQESeFJIwGx8EbkoOQOC/QbQoUyRQQqJnQLRZIlIucSAnxNAiDJeO5miGIsYSJ",
	"JDkEYSBXBQTHgZCc0CRYhwHHt1eEFqVnqVecJITiDBVYSIjRL4zHGSCRYg5Iwgc59U0oIsahP9lrEGUm",
	"kX56jC6Co4tgchE8uQgQ4+gi+PUi8Mym9gfvS8IhDo7f2alDVz6X9Ri2+B0iGYTBh0nCJvbDW71lMXVl",
	"7r4yIXnBuD57gWUaHAcJkWm5mEYsn5EIc7bkMzPJRHIcXQOfESqBU5zZz4Xepl3glAh5IiHv67TAXJKI",
	"FJjKq4iV1CPvn8t8ARyxJSoFcIFuU9ZoFGHEjQiXjCOZEoGK8o8/MmipmlD55HEjR7XVBLhWS5nnmK/U",
	"ql9xWAbHwf/NGojOLD5n9hzn9u11GNwQuAV+pUE2cnQD7WZ8isVVkeGV0mT34L+kIFPgGsy4lClQSSKl",
	"YS0IlLrIruXgwGXBWAaYqtWMTq6IbxUDXyM1RLWwu8L75pFHeB0UNkuEHq36DrwbSGsM7RmnZziBPk6J",
	"hFwMCg+b4drlEBAOFnGikVgPHwGT+qDrWj6Yc6xRR+GDx0KeLgTLSgno7esTZScKMOpNvXyI8EIAlYgs",
	"EWUoZxwsVITfUUG2HLdEVHKuJq4OucVLqXkrSeyueq2WPar+XGIaq333VH9nE1dWum3cWbnISPRWeAxK",
	"Dw/t8rsJrD7MPgXWeM62vBYgRvhyx0UIJAnE1mgAqfEmII704XrBgfj6Qz0ZwjmjCcJZ1l7bEzd6NrHE",
	"JIN4x0OpOGUG6mPtFpZYdnOnBc3AXRfsIM8RaOiqs7Ovjlx2hKiFzx4RapyzJ+cAbRy75BspvgFEmUQr",
	"kAPp5LAyTbjbeTl/bB8DHmv9nnh15uJFMK5mX6waa9slTtVOxhOnJJM4u9IH8uTq6qHNNNS5OSRESOA2",
	"sREjj/mFZWCYSAU6vZRPKm9HgG2UetyQ0tfMA2eCLhA6lhB2DNGnERfMfRnu5nGegcQk24/DKWX6GkTB",
	"qPD4mzF5wDkIQRgdTgR6Z12Hwd8JZPFzzhnvLxqb0/aU/KLMMZ1wwDFeZICch1Vad4MzEmP9ifLvJR+I",
	"iWpxj3Gr3BPnUM2mX0MyxbIKhs3825NGs0hYncYnhBeA4zdM/fc1RIzHfVFkTAjwWNxPOAeBMiYkwgkm",
	"VEi9Y1YY5Yx0Q43A+3PrvOaWyPROE2vTSdRE232oZh9qLsKY8FhHekvoVQE8Aipt7dMJGvUzZyW9L3TL",
	"KDqYT47m88M2t8LKReYQK2ajdrFBcanZ7qyJDnJc6dlVwwoJVmm9k4/0Jz3E7cOlNIucS2zIsjaqK+Hs",
	"Fg44qMNe5VhGqQ9XL5U1mJdQCjieSDZR/0d2xOgo9FrP8VKN8oUhXtvqpkl6kjbZjRyuxPVTlc8UKgtm",
	"FVqtQSBGs5U6wt1EadYw+nAq5dFD/BVxvXrfu3UG1G/W8qvE0VOsz1OeAo6BLxjm8TMs8WiSwxlXMxxN",
	"7sgxvR6NCmcqQzp6oGFUdlUZw4aEue3t0G0KqsxTBZ5JEJryaGyy3tVQeys7shddee/DTfQE2lMqvgGO",
	"ExgqkF8CplWBHHEmRNvBH/yKdHYmEBbob2OdvGWGroTkgK/7i/5omaNIJUxRKckNTG4JReb9kWErxx8G",
	"FzhlNFGVv38BBDf9zHZT8cZ3zLnvHrmN1E32+/mF7455WNmEnWDbRlxvgz14tFS5u23t7/bilCWEvob3",
	"JQjp4QVzb4KtQID0M4TjmINop2FmlCefLrAQtzYmemasHqvJckJPgSbqaEe+uyvIQenrKocNJS1DRIgS",
	"EEYZo8kkI5o3YtdAfQVsR/PVKepN++LNGWeLDPJndSVypwoFPhQZpqYeEQVEZEkitXvN2bHIYCny1yig",
	"aiOPDerCaZLBDWRuuWNeHx3MnPLLE8ZUFotp5FHBU02ic1iC3jkiMVBJlitCE5321qdsTocOuIEhUog+",
	"9BP3EstS+CuyF2/enCHzAopYDKPKepUmy8x7AJEyLlHa1pS9S/NuznywqyQKgyCkRm8vFvXTatO1PLzI",
	"bNy1J15iiblnr/rzaosEODq4COZHFwGSKWdlkqKL4NG3F4FfOT6+5S0l70swVFIz7Uivr2rs/pTPiFBO",
	"WVfg2wWmGRo9UVgde4v7NfzcW3MzcT8O13BDamtuyTBY7gzlMa/s86+FzWbG8PqWj9rcUGCJjNypjDQp",
	"pwmbjdfOmzsMNFnoOUgpI5YDWnKWDxCPXwtUAFduQiU2U31JVOZKo7+c/ByEwemr8/MgDN6cPHf02b7h",
	"GxLjU99i4wX6wOyic5KwixBXu7W0R2YXLhL3kVi8toz3rrnFczetQAd5KSRaACq1Izkcl2dsdxz1TRyF",
	"Ww2BETnHcPZyZp+gg5xQkpc5+g5FKeY4ksDFYWfu77b5LOuuRiUgLqn6QH5+jOK+zABRSXxcoFBOa+rK",
	"/77MSE2s9/m2UO7VaGvQjrYo+eRZiLzK1RwRlmrN4Dj458H83dHk+8t/Hb2bq/89ejeffHt5+NVW+Q3J",
	"ah1adzhQsz9kp9sG4Jl5d0beZ9079yAxSttNK1DZkNSI5i7tevurdF2a8tMZJJxlnz99FBMFiUVp5vwY",
	"4Dgm6t84O2udfsxUrd2da1G406P//vs/6BpWAimYa6A6/kYBFtO4h9jGVywxyTYSoUlzk3VgNPHr4Ugx",
	"jGSp7k5PPQxNtxsJdr+XV1096HmNGo4mTw7vQjx37q0MAEYway1Q3wvRdm7vF/bmc3TEGgzgG2LJ2UAI",
	"QZKhAnMB2qrMRcn2VKdZyHsNo+DJiVydRylYg/kBMAeuCqa6k11TZvrjZr1UyiJYrzUjZLraO8fg5AZL",
	"qM4RsbwAqT0Renp2onPxR5Mn1ZXGtCY46mj1xghZvR2EwQ1wYSY+ms6nc4VaVgDFBQmOg2+m8+k3JrVJ",
	"9RlmKeDMHCABaeps4JoNO4mD4+AnkC/MG7qE0g0OeuCj+VwnKoxKe3GGiyJTZSNhdPa7MD7VMGV9rTZU",
	"FXzAeaFPw663t5AOMTrrvhMGfkMiQEQgc8RVS43B8btLp/k7MIdEUQqR3gZOhFrQSudSDZ1lDeUsZtay",
	"NgnOoag/VXojr9T0LZNHGO5O1mHweH7kcWJMtpmGrrzagH93uW4J8CeQdT9w1jp4JUv3UyNQYcoDk3Ew",
	"ITezEcI0UlhmncYNI47OQSUYFL2QsnhFsxWKGLsmpo4V5UIo50IlshSqmF7QC3rmUIviGP02s1yjmDWE",
	"8EQTwr9NL6imF1z96quBwMAThPyBxav706h77bBuG4HkJaz3iKZWJ5MPSmpvSJRRBEIsy8zgadP6Vq7/",
	"v9s+2ncHno38o0PbO8B+2I2cUA0YFHHQhRLOxEZXc8oSROgQmB2D0ZVu21JctxNDBhL6nueUJayUfY/z",
	"2Jd+JQnESL2+J7egDsvKxjXYg/hPWbeLej3qKRHyre0jvMdQVN/0fHJvZbcG9LcKeBCk7/cyIvanBSKk",
	"LsqqPsxK+Obvy3U44H9/1CWqQLimAhGOdEG3d6cbuk+1nUwkvgbq9cYVn7onh9yla0f55KMH88lme9xe",
	"kX6urvn7h9+IZV0zDjheIQ2fja650rOD9w2ealb1fw0lgJamsPTn3kJ2u3W4J4SKLCmt09p39te/rvI7",
	"nOqar+MLNasrhi++DKV6HymcSyDvyXH4OOoHTui2oMPsMHbQ8XnlcvcKU3PYGqkmnlX670K0becztxlW",
	"zD6qJyfP1o75d32yLDkV7R5aw0WEpkk1rOgJtRXbttnqfrZtICpBq/qgN6Ne7XOi5I85EcwfKU1Bb5tq",
	"zTd1cQ5SJ17vPMQWcBL5LqCIeq75n+qmKTAiCbrgDh2UbKfBLvdoCt2Wag8SX7jqElWj759iFFVdUSkf",
	"HcA0mYbIKpgmpoRYsZIrxR/uYjTqzccPf6SqR0N/uWnJSnqHMJP2NFQbDabI6ZB2OJx6QN+s627yoSD+",
	"cnVed1jvCZftHnF/eeBgcb/hu2xWa2RY0bau+DwusCc8m/r8lZxM6wvdXl1+AYaqIfcJRqp1uVghranh",
	"wFpBaLsVqg1VdvhXQtNeXMMXCirj7JdMlWd1i2ynvmg7KnsL1XTrbaCazzAXmukY6kxwbpNMeWK/7bs5",
	"JyMmik/MVtqsRlwambs79CZt5o7Mfp19P5WK7zLugWkOtyPGd6PT9FziKIKihvKfmJsZ54AY73WR72qP",
	"fwI78qyCn9POuptVGrggXBmLbbLcbI4b/bz9qvY2L/8Sf9CdhE1/gmZbkWSI68ILFforE/bHd9SQ9yXo",
	"3hnr+TOSE/2DFrUsY1hi3ZD77dzT8JObFYPjo/lcNyzav3w3+f3WZPy+hBAtsIAnjydAIxZDrDIuwbh2",
	"aAVOiPmKwxS9UiKtOjCXhAu58SBmltZJupeo+wxQ3V/o8eDMvqJPsc8M9rb9W0wHVqgQH25D5Oyj+ceW",
	"bLb9syJbIDrUSubJQqrFR+ch/ha0B1CzPbpHyfa49js9n38yYvf7CekIRoLQJIMKd7oad3+twgM5vQa/",
	"qRBT8iw4DmbB+nL9vwAAAP//mvTp8RlRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
