/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as authImport } from './routes/__auth'
import { Route as IndexImport } from './routes/index'
import { Route as authLookupImport } from './routes/__auth/lookup'
import { Route as authLeaderboardImport } from './routes/__auth/leaderboard'
import { Route as authHeadToHeadImport } from './routes/__auth/head-to-head'
import { Route as authDashboardImport } from './routes/__auth/dashboard'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLookupRoute = authLookupImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => authRoute,
} as any)

const authLeaderboardRoute = authLeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => authRoute,
} as any)

const authHeadToHeadRoute = authHeadToHeadImport.update({
  id: '/head-to-head',
  path: '/head-to-head',
  getParentRoute: () => authRoute,
} as any)

const authDashboardRoute = authDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/__auth/dashboard': {
      id: '/__auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardImport
      parentRoute: typeof authImport
    }
    '/__auth/head-to-head': {
      id: '/__auth/head-to-head'
      path: '/head-to-head'
      fullPath: '/head-to-head'
      preLoaderRoute: typeof authHeadToHeadImport
      parentRoute: typeof authImport
    }
    '/__auth/leaderboard': {
      id: '/__auth/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof authLeaderboardImport
      parentRoute: typeof authImport
    }
    '/__auth/lookup': {
      id: '/__auth/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof authLookupImport
      parentRoute: typeof authImport
    }
  }
}

// Create and export the route tree

interface authRouteChildren {
  authDashboardRoute: typeof authDashboardRoute
  authHeadToHeadRoute: typeof authHeadToHeadRoute
  authLeaderboardRoute: typeof authLeaderboardRoute
  authLookupRoute: typeof authLookupRoute
}

const authRouteChildren: authRouteChildren = {
  authDashboardRoute: authDashboardRoute,
  authHeadToHeadRoute: authHeadToHeadRoute,
  authLeaderboardRoute: authLeaderboardRoute,
  authLookupRoute: authLookupRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof authDashboardRoute
  '/head-to-head': typeof authHeadToHeadRoute
  '/leaderboard': typeof authLeaderboardRoute
  '/lookup': typeof authLookupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof authDashboardRoute
  '/head-to-head': typeof authHeadToHeadRoute
  '/leaderboard': typeof authLeaderboardRoute
  '/lookup': typeof authLookupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__auth': typeof authRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/__auth/dashboard': typeof authDashboardRoute
  '/__auth/head-to-head': typeof authHeadToHeadRoute
  '/__auth/leaderboard': typeof authLeaderboardRoute
  '/__auth/lookup': typeof authLookupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/dashboard'
    | '/head-to-head'
    | '/leaderboard'
    | '/lookup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/dashboard'
    | '/head-to-head'
    | '/leaderboard'
    | '/lookup'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/login'
    | '/register'
    | '/__auth/dashboard'
    | '/__auth/head-to-head'
    | '/__auth/leaderboard'
    | '/__auth/lookup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__auth",
        "/login",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/dashboard",
        "/__auth/head-to-head",
        "/__auth/leaderboard",
        "/__auth/lookup"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/__auth/dashboard": {
      "filePath": "__auth/dashboard.tsx",
      "parent": "/__auth"
    },
    "/__auth/head-to-head": {
      "filePath": "__auth/head-to-head.tsx",
      "parent": "/__auth"
    },
    "/__auth/leaderboard": {
      "filePath": "__auth/leaderboard.tsx",
      "parent": "/__auth"
    },
    "/__auth/lookup": {
      "filePath": "__auth/lookup.tsx",
      "parent": "/__auth"
    }
  }
}
ROUTE_MANIFEST_END */
