// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO user_tokens (user_id, token, context, sent_to, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
`

type CreateTokenParams struct {
	UserID       int64
	Token        []byte
	TokenContext string
	SentTo       pgtype.Text
	CreatedAt    pgtype.Timestamp
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.UserID,
		arg.Token,
		arg.TokenContext,
		arg.SentTo,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, avatar, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  '01',
  $4,
  $5
)
RETURNING id, name, email, avatar
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type CreateUserRow struct {
	ID     int64
	Name   string
	Email  string
	Avatar string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM user_tokens
WHERE token = $1
  AND context IN ('api-token-long', 'api-token-short', 'api-token')
`

func (q *Queries) DeleteToken(ctx context.Context, token []byte) error {
	_, err := q.db.Exec(ctx, deleteToken, token)
	return err
}

const getCredentialsByEmail = `-- name: GetCredentialsByEmail :one
SELECT id, name, email, password_hash, avatar
FROM users
WHERE email = $1
`

type GetCredentialsByEmailRow struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Avatar       string
}

func (q *Queries) GetCredentialsByEmail(ctx context.Context, email string) (GetCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsByEmail, email)
	var i GetCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT u.id, u.name, u.email, u.avatar
FROM users u
JOIN user_tokens t ON t.user_id = u.id
WHERE t.token = $1
  AND t.sent_to = u.email
  AND (
    (t.context = 'api-token-short' AND t.created_at > $2)
    OR (t.context = 'api-token-long' AND t.created_at > $3)
  )
`

type GetSessionByTokenParams struct {
	Token       []byte
	ShortCutoff pgtype.Timestamp
	LongCutoff  pgtype.Timestamp
}

type GetSessionByTokenRow struct {
	ID     int64
	Name   string
	Email  string
	Avatar string
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, arg.Token, arg.ShortCutoff, arg.LongCutoff)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}

const updateAvatar = `-- name: UpdateAvatar :one
UPDATE users
SET avatar = $1, updated_at = $2
WHERE id = $3
RETURNING id, name, email, avatar
`

type UpdateAvatarParams struct {
	Avatar    string
	UpdatedAt pgtype.Timestamp
	UserID    int64
}

type UpdateAvatarRow struct {
	ID     int64
	Name   string
	Email  string
	Avatar string
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (UpdateAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateAvatar, arg.Avatar, arg.UpdatedAt, arg.UserID)
	var i UpdateAvatarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}
