// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              int64
	Name            string
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamp
	Avatar          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type UserToken struct {
	ID        int64
	UserID    int64
	Token     []byte
	Context   string
	SentTo    pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Wordle struct {
	Number    int32
	Solution  pgtype.Text
	Word      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type WordleEntry struct {
	ID        int64
	UserID    int64
	WordleID  int32
	Score     string
	RawInput  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
