// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWordleEntry(ctx context.Context, arg CreateWordleEntryParams) (CreateWordleEntryRow, error)
	DeleteToken(ctx context.Context, token []byte) error
	EnsureWordle(ctx context.Context, arg EnsureWordleParams) error
	GetArchiveEntries(ctx context.Context, wordleID int32) ([]GetArchiveEntriesRow, error)
	GetArchiveList(ctx context.Context, arg GetArchiveListParams) ([]GetArchiveListRow, error)
	GetCredentialsByEmail(ctx context.Context, email string) (GetCredentialsByEmailRow, error)
	GetHeadToHeadMatches(ctx context.Context, arg GetHeadToHeadMatchesParams) ([]GetHeadToHeadMatchesRow, error)
	GetScoreDistribution(ctx context.Context, userID int64) ([]GetScoreDistributionRow, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error)
	GetSharedWordleIDsForUsers(ctx context.Context, arg GetSharedWordleIDsForUsersParams) ([]int32, error)
	GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error)
	GetUserScoreDistributionForUsers(ctx context.Context, arg GetUserScoreDistributionForUsersParams) ([]GetUserScoreDistributionForUsersRow, error)
	GetUserWinningWordleIDsForUsers(ctx context.Context, arg GetUserWinningWordleIDsForUsersParams) ([]GetUserWinningWordleIDsForUsersRow, error)
	GetWinningWordleIDs(ctx context.Context, userID int64) ([]int32, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (UpdateAvatarRow, error)
}

var _ Querier = (*Queries)(nil)
