// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, avatar
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID     int64
	Name   string
	Avatar string
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Avatar)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, avatar
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID     int64
	Name   string
	Avatar string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
