// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wordles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWordleEntry = `-- name: CreateWordleEntry :one
INSERT INTO wordle_entries (user_id, wordle_id, score, raw_input, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (user_id, wordle_id) DO NOTHING
RETURNING id, wordle_id, score, raw_input, created_at
`

type CreateWordleEntryParams struct {
	UserID    int64
	WordleID  int32
	Score     string
	RawInput  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type CreateWordleEntryRow struct {
	ID        int64
	WordleID  int32
	Score     string
	RawInput  pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateWordleEntry(ctx context.Context, arg CreateWordleEntryParams) (CreateWordleEntryRow, error) {
	row := q.db.QueryRow(ctx, createWordleEntry,
		arg.UserID,
		arg.WordleID,
		arg.Score,
		arg.RawInput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateWordleEntryRow
	err := row.Scan(
		&i.ID,
		&i.WordleID,
		&i.Score,
		&i.RawInput,
		&i.CreatedAt,
	)
	return i, err
}

const ensureWordle = `-- name: EnsureWordle :exec
INSERT INTO wordles (number, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (number) DO NOTHING
`

type EnsureWordleParams struct {
	Number    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) EnsureWordle(ctx context.Context, arg EnsureWordleParams) error {
	_, err := q.db.Exec(ctx, ensureWordle, arg.Number, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const getArchiveEntries = `-- name: GetArchiveEntries :many
SELECT user_id, score, raw_input, created_at
FROM wordle_entries
WHERE wordle_id = $1
`

type GetArchiveEntriesRow struct {
	UserID    int64
	Score     string
	RawInput  pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetArchiveEntries(ctx context.Context, wordleID int32) ([]GetArchiveEntriesRow, error) {
	rows, err := q.db.Query(ctx, getArchiveEntries, wordleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveEntriesRow
	for rows.Next() {
		var i GetArchiveEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Score,
			&i.RawInput,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveList = `-- name: GetArchiveList :many
WITH summary AS (
  SELECT
    we.wordle_id,
    COUNT(*)::bigint AS participant_count,
    MIN(CASE WHEN we.score = 'X' THEN 7 ELSE CAST(we.score AS INTEGER) END)::int AS best_score,
    COUNT(*) FILTER (WHERE we.score != 'X')::bigint AS solved_count,
    COUNT(*) FILTER (WHERE we.score = 'X')::bigint AS failed_count
  FROM wordle_entries we
  WHERE ($3::int = 0 OR we.wordle_id < $3::int)
  GROUP BY we.wordle_id
)
SELECT
  s.wordle_id,
  s.participant_count,
  COALESCE(viewer.has_played, FALSE)::boolean AS viewer_has_played,
  COALESCE(viewer.score, '')::text AS viewer_score,
  viewer.created_at::timestamp AS viewer_created_at,
  s.best_score,
  COUNT(*) FILTER (
    WHERE CASE WHEN we.score = 'X' THEN 7 ELSE CAST(we.score AS INTEGER) END = s.best_score
  )::bigint AS best_count,
  s.solved_count,
  s.failed_count
FROM summary s
JOIN wordle_entries we ON we.wordle_id = s.wordle_id
LEFT JOIN LATERAL (
  SELECT TRUE::boolean AS has_played, score, created_at
  FROM wordle_entries viewer_entry
  WHERE viewer_entry.wordle_id = s.wordle_id
    AND viewer_entry.user_id = $1
  LIMIT 1
) AS viewer ON true
GROUP BY
  s.wordle_id,
  s.participant_count,
  viewer.has_played,
  viewer.score,
  viewer.created_at,
  s.best_score,
  s.solved_count,
  s.failed_count
ORDER BY s.wordle_id DESC
LIMIT $2
`

type GetArchiveListParams struct {
	UserID    int64
	PageLimit int32
	BeforeID  int32
}

type GetArchiveListRow struct {
	WordleID         int32
	ParticipantCount int64
	ViewerHasPlayed  bool
	ViewerScore      string
	ViewerCreatedAt  pgtype.Timestamp
	BestScore        int32
	BestCount        int64
	SolvedCount      int64
	FailedCount      int64
}

func (q *Queries) GetArchiveList(ctx context.Context, arg GetArchiveListParams) ([]GetArchiveListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveList, arg.UserID, arg.PageLimit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveListRow
	for rows.Next() {
		var i GetArchiveListRow
		if err := rows.Scan(
			&i.WordleID,
			&i.ParticipantCount,
			&i.ViewerHasPlayed,
			&i.ViewerScore,
			&i.ViewerCreatedAt,
			&i.BestScore,
			&i.BestCount,
			&i.SolvedCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeadToHeadMatches = `-- name: GetHeadToHeadMatches :many
SELECT we1.wordle_id, we1.score AS user_score, we2.score AS opponent_score, we1.created_at
FROM wordle_entries we1
JOIN wordle_entries we2 ON we1.wordle_id = we2.wordle_id
WHERE we1.user_id = $1
  AND we2.user_id = $2
ORDER BY we1.wordle_id DESC
`

type GetHeadToHeadMatchesParams struct {
	UserID     int64
	OpponentID int64
}

type GetHeadToHeadMatchesRow struct {
	WordleID      int32
	UserScore     string
	OpponentScore string
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) GetHeadToHeadMatches(ctx context.Context, arg GetHeadToHeadMatchesParams) ([]GetHeadToHeadMatchesRow, error) {
	rows, err := q.db.Query(ctx, getHeadToHeadMatches, arg.UserID, arg.OpponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeadToHeadMatchesRow
	for rows.Next() {
		var i GetHeadToHeadMatchesRow
		if err := rows.Scan(
			&i.WordleID,
			&i.UserScore,
			&i.OpponentScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoreDistribution = `-- name: GetScoreDistribution :many
SELECT score, COUNT(*) AS count
FROM wordle_entries
WHERE user_id = $1
GROUP BY score
ORDER BY score
`

type GetScoreDistributionRow struct {
	Score string
	Count int64
}

func (q *Queries) GetScoreDistribution(ctx context.Context, userID int64) ([]GetScoreDistributionRow, error) {
	rows, err := q.db.Query(ctx, getScoreDistribution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScoreDistributionRow
	for rows.Next() {
		var i GetScoreDistributionRow
		if err := rows.Scan(&i.Score, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedWordleIDsForUsers = `-- name: GetSharedWordleIDsForUsers :many
SELECT wordle_id
FROM wordle_entries
WHERE user_id = ANY($1::bigint[])
GROUP BY wordle_id
HAVING COUNT(DISTINCT user_id) = $2
ORDER BY wordle_id DESC
`

type GetSharedWordleIDsForUsersParams struct {
	UserIds   []int64
	UserCount int64
}

func (q *Queries) GetSharedWordleIDsForUsers(ctx context.Context, arg GetSharedWordleIDsForUsersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getSharedWordleIDsForUsers, arg.UserIds, arg.UserCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var wordle_id int32
		if err := rows.Scan(&wordle_id); err != nil {
			return nil, err
		}
		items = append(items, wordle_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserScoreDistributionForUsers = `-- name: GetUserScoreDistributionForUsers :many
SELECT user_id, score, COUNT(*) AS count
FROM wordle_entries
WHERE user_id = ANY($1::bigint[])
  AND wordle_id = ANY($2::int[])
GROUP BY user_id, score
`

type GetUserScoreDistributionForUsersParams struct {
	UserIds   []int64
	WordleIds []int32
}

type GetUserScoreDistributionForUsersRow struct {
	UserID int64
	Score  string
	Count  int64
}

func (q *Queries) GetUserScoreDistributionForUsers(ctx context.Context, arg GetUserScoreDistributionForUsersParams) ([]GetUserScoreDistributionForUsersRow, error) {
	rows, err := q.db.Query(ctx, getUserScoreDistributionForUsers, arg.UserIds, arg.WordleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserScoreDistributionForUsersRow
	for rows.Next() {
		var i GetUserScoreDistributionForUsersRow
		if err := rows.Scan(&i.UserID, &i.Score, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWinningWordleIDsForUsers = `-- name: GetUserWinningWordleIDsForUsers :many
SELECT user_id, wordle_id
FROM wordle_entries
WHERE user_id = ANY($1::bigint[])
  AND wordle_id = ANY($2::int[])
  AND score != 'X'
ORDER BY user_id, wordle_id DESC
`

type GetUserWinningWordleIDsForUsersParams struct {
	UserIds   []int64
	WordleIds []int32
}

type GetUserWinningWordleIDsForUsersRow struct {
	UserID   int64
	WordleID int32
}

func (q *Queries) GetUserWinningWordleIDsForUsers(ctx context.Context, arg GetUserWinningWordleIDsForUsersParams) ([]GetUserWinningWordleIDsForUsersRow, error) {
	rows, err := q.db.Query(ctx, getUserWinningWordleIDsForUsers, arg.UserIds, arg.WordleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWinningWordleIDsForUsersRow
	for rows.Next() {
		var i GetUserWinningWordleIDsForUsersRow
		if err := rows.Scan(&i.UserID, &i.WordleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWinningWordleIDs = `-- name: GetWinningWordleIDs :many
SELECT wordle_id
FROM wordle_entries
WHERE user_id = $1
  AND score != 'X'
ORDER BY wordle_id DESC
`

func (q *Queries) GetWinningWordleIDs(ctx context.Context, userID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, getWinningWordleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var wordle_id int32
		if err := rows.Scan(&wordle_id); err != nil {
			return nil, err
		}
		items = append(items, wordle_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
