// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"github.com/icarofr/wordle-tracker/internal/auth"
	"github.com/icarofr/wordle-tracker/internal/users"
	"github.com/icarofr/wordle-tracker/internal/wordles"
	"sync"
)

// Ensure, that authServiceMock does implement authService.
// If this is not the case, regenerate this file with moq.
var _ authService = &authServiceMock{}

// authServiceMock is a mock implementation of authService.
//
//	func TestSomethingThatUsesauthService(t *testing.T) {
//
//		// make and configure a mocked authService
//		mockedauthService := &authServiceMock{
//			LoginFunc: func(ctx context.Context, input auth.LoginInput) (*auth.SessionUser, string, error) {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func(ctx context.Context, authorization string) error {
//				panic("mock out the Logout method")
//			},
//			RegisterFunc: func(ctx context.Context, input auth.RegisterInput) (*auth.SessionUser, string, error) {
//				panic("mock out the Register method")
//			},
//			UpdateAvatarFunc: func(ctx context.Context, userID int64, avatar string) (*auth.SessionUser, error) {
//				panic("mock out the UpdateAvatar method")
//			},
//			UserByAuthorizationFunc: func(ctx context.Context, authorization string) (*auth.SessionUser, error) {
//				panic("mock out the UserByAuthorization method")
//			},
//		}
//
//		// use mockedauthService in code that requires authService
//		// and then make assertions.
//
//	}
type authServiceMock struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, input auth.LoginInput) (*auth.SessionUser, string, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, authorization string) error

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, input auth.RegisterInput) (*auth.SessionUser, string, error)

	// UpdateAvatarFunc mocks the UpdateAvatar method.
	UpdateAvatarFunc func(ctx context.Context, userID int64, avatar string) (*auth.SessionUser, error)

	// UserByAuthorizationFunc mocks the UserByAuthorization method.
	UserByAuthorizationFunc func(ctx context.Context, authorization string) (*auth.SessionUser, error)

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input auth.LoginInput
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Authorization is the authorization argument value.
			Authorization string
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input auth.RegisterInput
		}
		// UpdateAvatar holds details about calls to the UpdateAvatar method.
		UpdateAvatar []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// Avatar is the avatar argument value.
			Avatar string
		}
		// UserByAuthorization holds details about calls to the UserByAuthorization method.
		UserByAuthorization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Authorization is the authorization argument value.
			Authorization string
		}
	}
	lockLogin               sync.RWMutex
	lockLogout              sync.RWMutex
	lockRegister            sync.RWMutex
	lockUpdateAvatar        sync.RWMutex
	lockUserByAuthorization sync.RWMutex
}

// Login calls LoginFunc.
func (mock *authServiceMock) Login(ctx context.Context, input auth.LoginInput) (*auth.SessionUser, string, error) {
	if mock.LoginFunc == nil {
		panic("authServiceMock.LoginFunc: method is nil but authService.Login was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input auth.LoginInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, input)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedauthService.LoginCalls())
func (mock *authServiceMock) LoginCalls() []struct {
	Ctx   context.Context
	Input auth.LoginInput
} {
	var calls []struct {
		Ctx   context.Context
		Input auth.LoginInput
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *authServiceMock) Logout(ctx context.Context, authorization string) error {
	if mock.LogoutFunc == nil {
		panic("authServiceMock.LogoutFunc: method is nil but authService.Logout was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Authorization string
	}{
		Ctx:           ctx,
		Authorization: authorization,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, authorization)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedauthService.LogoutCalls())
func (mock *authServiceMock) LogoutCalls() []struct {
	Ctx           context.Context
	Authorization string
} {
	var calls []struct {
		Ctx           context.Context
		Authorization string
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *authServiceMock) Register(ctx context.Context, input auth.RegisterInput) (*auth.SessionUser, string, error) {
	if mock.RegisterFunc == nil {
		panic("authServiceMock.RegisterFunc: method is nil but authService.Register was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input auth.RegisterInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, input)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedauthService.RegisterCalls())
func (mock *authServiceMock) RegisterCalls() []struct {
	Ctx   context.Context
	Input auth.RegisterInput
} {
	var calls []struct {
		Ctx   context.Context
		Input auth.RegisterInput
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// UpdateAvatar calls UpdateAvatarFunc.
func (mock *authServiceMock) UpdateAvatar(ctx context.Context, userID int64, avatar string) (*auth.SessionUser, error) {
	if mock.UpdateAvatarFunc == nil {
		panic("authServiceMock.UpdateAvatarFunc: method is nil but authService.UpdateAvatar was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		Avatar string
	}{
		Ctx:    ctx,
		UserID: userID,
		Avatar: avatar,
	}
	mock.lockUpdateAvatar.Lock()
	mock.calls.UpdateAvatar = append(mock.calls.UpdateAvatar, callInfo)
	mock.lockUpdateAvatar.Unlock()
	return mock.UpdateAvatarFunc(ctx, userID, avatar)
}

// UpdateAvatarCalls gets all the calls that were made to UpdateAvatar.
// Check the length with:
//
//	len(mockedauthService.UpdateAvatarCalls())
func (mock *authServiceMock) UpdateAvatarCalls() []struct {
	Ctx    context.Context
	UserID int64
	Avatar string
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		Avatar string
	}
	mock.lockUpdateAvatar.RLock()
	calls = mock.calls.UpdateAvatar
	mock.lockUpdateAvatar.RUnlock()
	return calls
}

// UserByAuthorization calls UserByAuthorizationFunc.
func (mock *authServiceMock) UserByAuthorization(ctx context.Context, authorization string) (*auth.SessionUser, error) {
	if mock.UserByAuthorizationFunc == nil {
		panic("authServiceMock.UserByAuthorizationFunc: method is nil but authService.UserByAuthorization was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Authorization string
	}{
		Ctx:           ctx,
		Authorization: authorization,
	}
	mock.lockUserByAuthorization.Lock()
	mock.calls.UserByAuthorization = append(mock.calls.UserByAuthorization, callInfo)
	mock.lockUserByAuthorization.Unlock()
	return mock.UserByAuthorizationFunc(ctx, authorization)
}

// UserByAuthorizationCalls gets all the calls that were made to UserByAuthorization.
// Check the length with:
//
//	len(mockedauthService.UserByAuthorizationCalls())
func (mock *authServiceMock) UserByAuthorizationCalls() []struct {
	Ctx           context.Context
	Authorization string
} {
	var calls []struct {
		Ctx           context.Context
		Authorization string
	}
	mock.lockUserByAuthorization.RLock()
	calls = mock.calls.UserByAuthorization
	mock.lockUserByAuthorization.RUnlock()
	return calls
}

// Ensure, that usersServiceMock does implement usersService.
// If this is not the case, regenerate this file with moq.
var _ usersService = &usersServiceMock{}

// usersServiceMock is a mock implementation of usersService.
//
//	func TestSomethingThatUsesusersService(t *testing.T) {
//
//		// make and configure a mocked usersService
//		mockedusersService := &usersServiceMock{
//			GetFunc: func(ctx context.Context, id int64) (*users.User, error) {
//				panic("mock out the Get method")
//			},
//			GetOpponentFunc: func(ctx context.Context, userID int64, opponentID int64) (*users.User, error) {
//				panic("mock out the GetOpponent method")
//			},
//			ListFunc: func(ctx context.Context) ([]users.User, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedusersService in code that requires usersService
//		// and then make assertions.
//
//	}
type usersServiceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*users.User, error)

	// GetOpponentFunc mocks the GetOpponent method.
	GetOpponentFunc func(ctx context.Context, userID int64, opponentID int64) (*users.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]users.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetOpponent holds details about calls to the GetOpponent method.
		GetOpponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// OpponentID is the opponentID argument value.
			OpponentID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet         sync.RWMutex
	lockGetOpponent sync.RWMutex
	lockList        sync.RWMutex
}

// Get calls GetFunc.
func (mock *usersServiceMock) Get(ctx context.Context, id int64) (*users.User, error) {
	if mock.GetFunc == nil {
		panic("usersServiceMock.GetFunc: method is nil but usersService.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedusersService.GetCalls())
func (mock *usersServiceMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetOpponent calls GetOpponentFunc.
func (mock *usersServiceMock) GetOpponent(ctx context.Context, userID int64, opponentID int64) (*users.User, error) {
	if mock.GetOpponentFunc == nil {
		panic("usersServiceMock.GetOpponentFunc: method is nil but usersService.GetOpponent was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     int64
		OpponentID int64
	}{
		Ctx:        ctx,
		UserID:     userID,
		OpponentID: opponentID,
	}
	mock.lockGetOpponent.Lock()
	mock.calls.GetOpponent = append(mock.calls.GetOpponent, callInfo)
	mock.lockGetOpponent.Unlock()
	return mock.GetOpponentFunc(ctx, userID, opponentID)
}

// GetOpponentCalls gets all the calls that were made to GetOpponent.
// Check the length with:
//
//	len(mockedusersService.GetOpponentCalls())
func (mock *usersServiceMock) GetOpponentCalls() []struct {
	Ctx        context.Context
	UserID     int64
	OpponentID int64
} {
	var calls []struct {
		Ctx        context.Context
		UserID     int64
		OpponentID int64
	}
	mock.lockGetOpponent.RLock()
	calls = mock.calls.GetOpponent
	mock.lockGetOpponent.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *usersServiceMock) List(ctx context.Context) ([]users.User, error) {
	if mock.ListFunc == nil {
		panic("usersServiceMock.ListFunc: method is nil but usersService.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedusersService.ListCalls())
func (mock *usersServiceMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Ensure, that wordlesServiceMock does implement wordlesService.
// If this is not the case, regenerate this file with moq.
var _ wordlesService = &wordlesServiceMock{}

// wordlesServiceMock is a mock implementation of wordlesService.
//
//	func TestSomethingThatUseswordlesService(t *testing.T) {
//
//		// make and configure a mocked wordlesService
//		mockedwordlesService := &wordlesServiceMock{
//			ArchiveDetailFunc: func(ctx context.Context, viewerID int64, wordleID int, players []wordles.Player) (*wordles.ArchiveDetail, error) {
//				panic("mock out the ArchiveDetail method")
//			},
//			ArchiveListFunc: func(ctx context.Context, viewerID int64, beforeID int, limit int) ([]wordles.ArchiveListItem, bool, error) {
//				panic("mock out the ArchiveList method")
//			},
//			HeadToHeadFunc: func(ctx context.Context, userID int64, opponentID int64) (*wordles.HeadToHeadResult, error) {
//				panic("mock out the HeadToHead method")
//			},
//			LeaderboardFunc: func(ctx context.Context, players []wordles.Player) (*wordles.LeaderboardData, error) {
//				panic("mock out the Leaderboard method")
//			},
//			StatsFunc: func(ctx context.Context, userID int64) (*wordles.Stats, error) {
//				panic("mock out the Stats method")
//			},
//			SubmitFunc: func(ctx context.Context, userID int64, rawInput string) (*wordles.Entry, error) {
//				panic("mock out the Submit method")
//			},
//		}
//
//		// use mockedwordlesService in code that requires wordlesService
//		// and then make assertions.
//
//	}
type wordlesServiceMock struct {
	// ArchiveDetailFunc mocks the ArchiveDetail method.
	ArchiveDetailFunc func(ctx context.Context, viewerID int64, wordleID int, players []wordles.Player) (*wordles.ArchiveDetail, error)

	// ArchiveListFunc mocks the ArchiveList method.
	ArchiveListFunc func(ctx context.Context, viewerID int64, beforeID int, limit int) ([]wordles.ArchiveListItem, bool, error)

	// HeadToHeadFunc mocks the HeadToHead method.
	HeadToHeadFunc func(ctx context.Context, userID int64, opponentID int64) (*wordles.HeadToHeadResult, error)

	// LeaderboardFunc mocks the Leaderboard method.
	LeaderboardFunc func(ctx context.Context, players []wordles.Player) (*wordles.LeaderboardData, error)

	// StatsFunc mocks the Stats method.
	StatsFunc func(ctx context.Context, userID int64) (*wordles.Stats, error)

	// SubmitFunc mocks the Submit method.
	SubmitFunc func(ctx context.Context, userID int64, rawInput string) (*wordles.Entry, error)

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveDetail holds details about calls to the ArchiveDetail method.
		ArchiveDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ViewerID is the viewerID argument value.
			ViewerID int64
			// WordleID is the wordleID argument value.
			WordleID int
			// Players is the players argument value.
			Players []wordles.Player
		}
		// ArchiveList holds details about calls to the ArchiveList method.
		ArchiveList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ViewerID is the viewerID argument value.
			ViewerID int64
			// BeforeID is the beforeID argument value.
			BeforeID int
			// Limit is the limit argument value.
			Limit int
		}
		// HeadToHead holds details about calls to the HeadToHead method.
		HeadToHead []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// OpponentID is the opponentID argument value.
			OpponentID int64
		}
		// Leaderboard holds details about calls to the Leaderboard method.
		Leaderboard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Players is the players argument value.
			Players []wordles.Player
		}
		// Stats holds details about calls to the Stats method.
		Stats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// Submit holds details about calls to the Submit method.
		Submit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// RawInput is the rawInput argument value.
			RawInput string
		}
	}
	lockArchiveDetail sync.RWMutex
	lockArchiveList   sync.RWMutex
	lockHeadToHead    sync.RWMutex
	lockLeaderboard   sync.RWMutex
	lockStats         sync.RWMutex
	lockSubmit        sync.RWMutex
}

// ArchiveDetail calls ArchiveDetailFunc.
func (mock *wordlesServiceMock) ArchiveDetail(ctx context.Context, viewerID int64, wordleID int, players []wordles.Player) (*wordles.ArchiveDetail, error) {
	if mock.ArchiveDetailFunc == nil {
		panic("wordlesServiceMock.ArchiveDetailFunc: method is nil but wordlesService.ArchiveDetail was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ViewerID int64
		WordleID int
		Players  []wordles.Player
	}{
		Ctx:      ctx,
		ViewerID: viewerID,
		WordleID: wordleID,
		Players:  players,
	}
	mock.lockArchiveDetail.Lock()
	mock.calls.ArchiveDetail = append(mock.calls.ArchiveDetail, callInfo)
	mock.lockArchiveDetail.Unlock()
	return mock.ArchiveDetailFunc(ctx, viewerID, wordleID, players)
}

// ArchiveDetailCalls gets all the calls that were made to ArchiveDetail.
// Check the length with:
//
//	len(mockedwordlesService.ArchiveDetailCalls())
func (mock *wordlesServiceMock) ArchiveDetailCalls() []struct {
	Ctx      context.Context
	ViewerID int64
	WordleID int
	Players  []wordles.Player
} {
	var calls []struct {
		Ctx      context.Context
		ViewerID int64
		WordleID int
		Players  []wordles.Player
	}
	mock.lockArchiveDetail.RLock()
	calls = mock.calls.ArchiveDetail
	mock.lockArchiveDetail.RUnlock()
	return calls
}

// ArchiveList calls ArchiveListFunc.
func (mock *wordlesServiceMock) ArchiveList(ctx context.Context, viewerID int64, beforeID int, limit int) ([]wordles.ArchiveListItem, bool, error) {
	if mock.ArchiveListFunc == nil {
		panic("wordlesServiceMock.ArchiveListFunc: method is nil but wordlesService.ArchiveList was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ViewerID int64
		BeforeID int
		Limit    int
	}{
		Ctx:      ctx,
		ViewerID: viewerID,
		BeforeID: beforeID,
		Limit:    limit,
	}
	mock.lockArchiveList.Lock()
	mock.calls.ArchiveList = append(mock.calls.ArchiveList, callInfo)
	mock.lockArchiveList.Unlock()
	return mock.ArchiveListFunc(ctx, viewerID, beforeID, limit)
}

// ArchiveListCalls gets all the calls that were made to ArchiveList.
// Check the length with:
//
//	len(mockedwordlesService.ArchiveListCalls())
func (mock *wordlesServiceMock) ArchiveListCalls() []struct {
	Ctx      context.Context
	ViewerID int64
	BeforeID int
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		ViewerID int64
		BeforeID int
		Limit    int
	}
	mock.lockArchiveList.RLock()
	calls = mock.calls.ArchiveList
	mock.lockArchiveList.RUnlock()
	return calls
}

// HeadToHead calls HeadToHeadFunc.
func (mock *wordlesServiceMock) HeadToHead(ctx context.Context, userID int64, opponentID int64) (*wordles.HeadToHeadResult, error) {
	if mock.HeadToHeadFunc == nil {
		panic("wordlesServiceMock.HeadToHeadFunc: method is nil but wordlesService.HeadToHead was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     int64
		OpponentID int64
	}{
		Ctx:        ctx,
		UserID:     userID,
		OpponentID: opponentID,
	}
	mock.lockHeadToHead.Lock()
	mock.calls.HeadToHead = append(mock.calls.HeadToHead, callInfo)
	mock.lockHeadToHead.Unlock()
	return mock.HeadToHeadFunc(ctx, userID, opponentID)
}

// HeadToHeadCalls gets all the calls that were made to HeadToHead.
// Check the length with:
//
//	len(mockedwordlesService.HeadToHeadCalls())
func (mock *wordlesServiceMock) HeadToHeadCalls() []struct {
	Ctx        context.Context
	UserID     int64
	OpponentID int64
} {
	var calls []struct {
		Ctx        context.Context
		UserID     int64
		OpponentID int64
	}
	mock.lockHeadToHead.RLock()
	calls = mock.calls.HeadToHead
	mock.lockHeadToHead.RUnlock()
	return calls
}

// Leaderboard calls LeaderboardFunc.
func (mock *wordlesServiceMock) Leaderboard(ctx context.Context, players []wordles.Player) (*wordles.LeaderboardData, error) {
	if mock.LeaderboardFunc == nil {
		panic("wordlesServiceMock.LeaderboardFunc: method is nil but wordlesService.Leaderboard was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Players []wordles.Player
	}{
		Ctx:     ctx,
		Players: players,
	}
	mock.lockLeaderboard.Lock()
	mock.calls.Leaderboard = append(mock.calls.Leaderboard, callInfo)
	mock.lockLeaderboard.Unlock()
	return mock.LeaderboardFunc(ctx, players)
}

// LeaderboardCalls gets all the calls that were made to Leaderboard.
// Check the length with:
//
//	len(mockedwordlesService.LeaderboardCalls())
func (mock *wordlesServiceMock) LeaderboardCalls() []struct {
	Ctx     context.Context
	Players []wordles.Player
} {
	var calls []struct {
		Ctx     context.Context
		Players []wordles.Player
	}
	mock.lockLeaderboard.RLock()
	calls = mock.calls.Leaderboard
	mock.lockLeaderboard.RUnlock()
	return calls
}

// Stats calls StatsFunc.
func (mock *wordlesServiceMock) Stats(ctx context.Context, userID int64) (*wordles.Stats, error) {
	if mock.StatsFunc == nil {
		panic("wordlesServiceMock.StatsFunc: method is nil but wordlesService.Stats was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockStats.Lock()
	mock.calls.Stats = append(mock.calls.Stats, callInfo)
	mock.lockStats.Unlock()
	return mock.StatsFunc(ctx, userID)
}

// StatsCalls gets all the calls that were made to Stats.
// Check the length with:
//
//	len(mockedwordlesService.StatsCalls())
func (mock *wordlesServiceMock) StatsCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockStats.RLock()
	calls = mock.calls.Stats
	mock.lockStats.RUnlock()
	return calls
}

// Submit calls SubmitFunc.
func (mock *wordlesServiceMock) Submit(ctx context.Context, userID int64, rawInput string) (*wordles.Entry, error) {
	if mock.SubmitFunc == nil {
		panic("wordlesServiceMock.SubmitFunc: method is nil but wordlesService.Submit was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   int64
		RawInput string
	}{
		Ctx:      ctx,
		UserID:   userID,
		RawInput: rawInput,
	}
	mock.lockSubmit.Lock()
	mock.calls.Submit = append(mock.calls.Submit, callInfo)
	mock.lockSubmit.Unlock()
	return mock.SubmitFunc(ctx, userID, rawInput)
}

// SubmitCalls gets all the calls that were made to Submit.
// Check the length with:
//
//	len(mockedwordlesService.SubmitCalls())
func (mock *wordlesServiceMock) SubmitCalls() []struct {
	Ctx      context.Context
	UserID   int64
	RawInput string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   int64
		RawInput string
	}
	mock.lockSubmit.RLock()
	calls = mock.calls.Submit
	mock.lockSubmit.RUnlock()
	return calls
}

// Ensure, that pingerMock does implement pinger.
// If this is not the case, regenerate this file with moq.
var _ pinger = &pingerMock{}

// pingerMock is a mock implementation of pinger.
//
//	func TestSomethingThatUsespinger(t *testing.T) {
//
//		// make and configure a mocked pinger
//		mockedpinger := &pingerMock{
//			PingContextFunc: func(ctx context.Context) error {
//				panic("mock out the PingContext method")
//			},
//		}
//
//		// use mockedpinger in code that requires pinger
//		// and then make assertions.
//
//	}
type pingerMock struct {
	// PingContextFunc mocks the PingContext method.
	PingContextFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// PingContext holds details about calls to the PingContext method.
		PingContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPingContext sync.RWMutex
}

// PingContext calls PingContextFunc.
func (mock *pingerMock) PingContext(ctx context.Context) error {
	if mock.PingContextFunc == nil {
		panic("pingerMock.PingContextFunc: method is nil but pinger.PingContext was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPingContext.Lock()
	mock.calls.PingContext = append(mock.calls.PingContext, callInfo)
	mock.lockPingContext.Unlock()
	return mock.PingContextFunc(ctx)
}

// PingContextCalls gets all the calls that were made to PingContext.
// Check the length with:
//
//	len(mockedpinger.PingContextCalls())
func (mock *pingerMock) PingContextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPingContext.RLock()
	calls = mock.calls.PingContext
	mock.lockPingContext.RUnlock()
	return calls
}
